image: phpunit/phpunit:5.0.3
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
         # - composer update
          - phpunit
          - cp report test-reports -r