image: phpunit/phpunit:5.0.3
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer install
          - phpunit
          - cp report test-reports -r