image: phpunit/phpunit:5.0.3
pipelines:
  default:
    - step:
        caches:
          - composer
        script:
          - composer update
          #- touch .env
          - cp .env.example .env
          - php artisan key:generate
          - cat .env
          - chmod 777 storage bootstrap/cache -Rv
          - touch storage/database.sqlite
          - vendor/bin/phpunit
          - cp report test-reports -r